version: '3'

services:
  meudindin-app:
    build: .
    depends_on:
      - meudindin-db
    ports:
      - "8080:8080"
      - "8000:8000"
  meudindin-db:
    image: "mariadb:10.4.8-bionic"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'meudindin'
    ports:
      - '3306:3306'
